### ISSUE TITLE
Some notes about the HF artifacts

### ISSUE THREAD

**Issue by NielsRogge** [cheryyunl/Make-An-Agent#1]
Hi there,

Congrats on releasing the models and dataset! Niels here from the open-source team at Hugging Face. I was wondering whether you would be up for making your dataset as a dedicated dataset repository, rather than adding them as part of the model repo. This way, people can do:

```python
from datasets import load_dataset

dataset = load_dataset("cheryyunl/make-an-agent")
```

? This would also ensure a dataset viewer, which allows people to easily discover and read the first few rows of the dataset in the browser. See here for a guide: https://huggingface.co/docs/datasets/loading.

Regarding the models, we usually prefer to have a single checkpoint per model repository, each with a dedicated model card. This way, download stats can work out-of-the-box as explained here: https://huggingface.co/docs/hub/models-uploading#upload-a-pytorch-model-using-huggingfacehub. This will also automatically link your models to the Space.

Let me know if you need any help!

**Comment by cheryyunl** [comment]
Thank you for your kind suggestion! We now are uploading the dataset on: https://huggingface.co/datasets/cheryyunl/Make-An-Agent
And we will update the model card and dataset card today, also update the README about how to use the dataset!

**Comment by NielsRogge** [comment]
Thanks a lot, also opened a PR to link the dataset to the paper: https://huggingface.co/cheryyunl/Make-An-Agent/discussions/1
