### ISSUE TITLE
Format of param tensor in data.pt

### ISSUE THREAD

**Issue by AmoghJuloori** [cheryyunl/Make-An-Agent#4]
Hey @cheryyunl , I would like to know about the param tensor too, which stores the parameters of the policy network for every checkpoint. I am trying to adapt this framework onto my own dataset that I have acquired by training with PPO instead of SAC. In my training dataset, I tried storing the parameters for every checkpoint, in a list, as it is given by the agent.state_dict() function, which returns a dictionary of the agent's parameters. This format doesn't allow me to train on my dataset, so I would like to ask for the format in which the parameters are stored in the tensor for every checkpoint. Thanks!

_Originally posted by @AmoghJuloori in https://github.com/cheryyunl/Make-An-Agent/issues/3#issuecomment-2269707564_

**Comment by cheryyunl** [comment]
You need to flatten the entire network into a vector and store it in 'param', as we mentioned in the paper. However, the exact size of the vector is up to the design of your autoencoder.

**Comment by AmoghJuloori** [comment]
Oh okay, thank you for the help!
