### ISSUE TITLE
Information about policy params in data.pt and thier corresponding metaworld tasks

### ISSUE THREAD

**Issue by jayaramreddy10** [cheryyunl/Make-An-Agent#5]
Hi, 

I have a query about the policy params. In your data.pt file, i can see 17286 policies (SAC) {self.data['param'].shape : torch.Size([17286, 22664])} and corresponding traj and task embeddings. But there is no information about what task that policy corresponds to (I mean which one of the 10 metaworld tasks). Could you please provide additional information on this regarding the corresponding task? 

Also, in paper its mentioned that policy network architecture used for MetaWorld is a 4-layer MLP with 128 hidden units, containing a total of 22,664 parameters. But you also mentioned in Dataset section that you collect 1500 policy networks for each task in MetaWorld and Robosuite. These networks are sourced from policy checkpoints during SAC (11 ) training. So, is the SAC same as the 4-layer MLP?

**Comment by cheryyunl** [comment]
We have updated the single task data in: https://huggingface.co/datasets/cheryyunl/Make-An-Agent/tree/main/train_data/single%20task
If you need the task information, please use the single task data. 
The policy structure is in: https://github.com/cheryyunl/Make-An-Agent/blob/1a111f767b7381125af4ccc366a20fad215719f5/PolicyGenerator/display/model.py#L19
same as the single RL policy.
